version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_build:
      # Generate the Sphinx configuration for this Jupyter Book so it builds.
      - "jupyter-book config sphinx ."

conda:
  environment: environment-docs.yml

python:
  install:
    - method: pip
      path: .

sphinx:
  builder: html
  fail_on_warning: false
