# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "pyscal3"
#author: The Jupyter Book Community
logo: docs/_static/pyscal_logo1.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "auto"

only_build_toc_files: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/pyiron/DGM_workshop
  path_to_book: book
  branch: main

notebook_interface            : "notebook"

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
    - amsmath
    - dollarmath
    - linkify
    - substitution
    - colon_fence

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_theme: pydata_sphinx_theme
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    html_sidebars:
      "**": []
