channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - cxx-compiler
  - pybind11
  - jupyterlab
  - numpy
  - scipy>=1.15
  - ase
  - pyyaml
  - matplotlib
  - plotly
  - ipywidgets
  - scikit-learn
